### ISSUE TITLE
What is the license on these?

### ISSUE THREAD

**Issue by russkel** [leereilly/emoji#2]
Hi there,

I love the icon set and I'd love to use them in a similar way that github does. You don't specify the license on these in the read me. Please enlighten me!

Thanks,

Russkel

**Comment by leereilly** [comment]
Hi @russkel,

That's a great question. I looked into a little and all I can tell you is that the `LICENSE` file currently reads:

```
octocat, squirrel, shipit
Copyright (c) 2013 GitHub Inc. All rights reserved.

bowtie, neckbeard, fu
Copyright (c) 2013 37signals, LLC. All rights reserved.

feelsgood, finnadie, goberserk, godmode, hurtrealbad, rage 1-4, suspect
Copyright (c) 2013 id Software. All rights reserved.

trollface
Copyright (c) 2013 whynne@deviantart. All rights reserved.

All other images
Copyright (c) 2013 Apple Inc. All rights reserved.
```

Per github/gemoji#23 it looks like the policy is _don't use it if you're not happy with the existing license_ :finnadie:

Cheers,
 Lee :beers:

**Comment by russkel** [comment]
Hi Lee. Thanks for looking that up for me. That is the weirdest issue I
have ever read. I guess the licence is "use it until someone decides to get
their lawyers to send you a letter". :)
